# Generated by Django 4.2.11 on 2025-02-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publié le'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publié le'),
        ),
    ]
