# Generated by Django 4.2.11 on 2025-03-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlindtestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blindtest_type', models.CharField(max_length=15)),
                ('blindtest_goodanwser', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BlindtestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blindtest_answer1', models.CharField(max_length=30)),
                ('blindtest_answer2', models.CharField(max_length=30)),
                ('blindtest_answer3', models.CharField(max_length=30)),
                ('blindtest_answer4', models.CharField(max_length=30)),
                ('blindtest_music', models.CharField(max_length=60)),
                ('blindtest_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blindtest.blindtestquestion')),
            ],
        ),
    ]
