# Generated by Django 4.2.11 on 2025-03-01 13:37

import blindtest.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blindtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindtestQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blindtest_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[(blindtest.enums.QuestionType['GENERAL'], 'general'), (blindtest.enums.QuestionType['GENRE'], 'genre'), (blindtest.enums.QuestionType['ARTISTE'], 'artiste')], max_length=20)),
                ('correct_answer', models.CharField(max_length=255)),
                ('choices', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GenreArtist',
            fields=[
                ('blindtestquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blindtest.blindtestquestion')),
            ],
            bases=('blindtest.blindtestquestion',),
        ),
        migrations.CreateModel(
            name='GenreQuestion',
            fields=[
                ('blindtestquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blindtest.blindtestquestion')),
            ],
            bases=('blindtest.blindtestquestion',),
        ),
    ]
